//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cityy> Cityy { get; set; }
        public virtual DbSet<Countryy> Countryy { get; set; }
        public virtual DbSet<Hotell> Hotell { get; set; }
        public virtual DbSet<Humann> Humann { get; set; }
        public virtual DbSet<Permit> Permit { get; set; }
        public virtual DbSet<Routee> Routee { get; set; }
        public virtual DbSet<Servicce> Servicce { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
