//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit
    {
        public int Id { get; set; }
        public Nullable<int> Route { get; set; }
        public Nullable<int> Hotell { get; set; }
        public Nullable<int> Humann { get; set; }
    
        public virtual Hotell Hotell1 { get; set; }
        public virtual Humann Humann1 { get; set; }
        public virtual Routee Routee { get; set; }
    }
}
